# Generated by Django 4.1.3 on 2022-12-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumbiniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_activate', models.BooleanField(blank=True, max_length=55, null=True)),
                ('display_order', models.IntegerField(max_length=10)),
            ],
        ),
    ]
